version: "3.8"

services:
  database:
    image: postgres
    container_name: db_fc
    ports:
      - ${DB_PORT}:5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=prod
    volumes:
      - pgdata:/data/postgres
